Change experiment id for the new seurat PBMC
hms-dbmi-cellenics/ui pull request #100
Opened 2021-02-04 19:32 UTC by JuanluOnieva-biomage

# Background
#### Link to issue 

Change the old experiments id (5e959f9c9f4b120771249001) with the one with the seurat object (5928a56c7cbff9de78974ab50765ed20)

#### Link to staging deployment URL 

#### Links to any Pull Requests related to this

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

2021-02-04 19:36 UTC, ivababukova submitted a review, later dismissed

2021-02-04 19:47 UTC, JuanluOnieva-biomage commented
I am getting this error when trying to deploy in staging:

`✖️ Not all deployment files could be found. Check the URLs and status codes printed above and try again.`

I think that it is becuase it fails during the checks..., but I also change the old experiment id by the new one.

2021-02-09 13:50 UTC, marcellp requested changes
Still having problems with the staging environment not rendering.

Can you make sure that the data set is uploaded to biomage-staging as well as production? I assume the problem is that the experiment ID is throwing a 404.

2021-02-10 14:49 UTC, marcellp approved these changes

2021-02-10 14:52 UTC, merged