Multisample experiment data processing with multiple configurations
hms-dbmi-cellenics/ui pull request #139
Opened 2021-03-05 13:27 UTC by cosa65

# Background
#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-592

#### Link to staging deployment URL 

#### Links to any Pull Requests related to this

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [x] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [x] Photo of a cute animal attached to this PR

![pudu](https://user-images.githubusercontent.com/8465903/110121590-57203c80-7d9d-11eb-8455-d30baa2d6fcf.jpeg)

2021-03-07 00:36 UTC, aerlaut commented on src/components/data-processing/CellSizeDistribution/CalculationConfig.jsx
> +  const [individualChangesWarningEnabled, setIndividualChangesWarningEnabled] = useState(false);
`Enabled` sounds like a settings that can be enabled/disabled. Would renaming this to `displayIndividualChangesWarning` capture the intent better?

2021-03-08 10:32 UTC, StefanBabukov requested changes
Does the Redux store support multiple configurations for multiple samples?

2021-03-08 10:32 UTC, StefanBabukov commented on src/pages/experiments/[experimentId]/data-processing/index.jsx
> +  ).children.map(
This will fail if the cellsets are not loaded. We should check if the cellsets are there and load them if not.

2021-03-08 10:45 UTC, cosa65 commented
> Does the Redux store support multiple configurations for multiple samples?

Yes, if you check one of the new `CalculationConfig`s you can see that I am creating a `sampleSpecificDiff`, which has a `sampleId` object.

This sampleId is also used in the `useSelector`s, so with this we can have individual configurations for each sample.

2021-03-08 11:29 UTC, StefanBabukov commented
I can see that the sample config loads when you make a change not preloaded when you open the processing step. Also there is an additional config which is not under a sample field
![image](https://user-images.githubusercontent.com/22479584/110315687-4298aa00-8012-11eb-9e7f-0544d2e6d432.png)
is this intentional?

2021-03-08 11:59 UTC, cosa65 commented
> There is additional filterSettings which are not under a sample field they seem not necessary.
> ![image](https://user-images.githubusercontent.com/22479584/110315687-4298aa00-8012-11eb-9e7f-0544d2e6d432.png)
> is this intentional?

They are the default values (in initialState), an example of them being used is here:

`(state) => state.experimentSettings.processing.cellSizeDistribution[sampleId]?.filterSettings
      || state.experimentSettings.processing.cellSizeDistribution.filterSettings,`

So what we are doing is getting the sample specific filterSettings, if they don't exist, then get the default ones (once we set specific sample settings then an entry for sampleId is created).

2021-03-08 12:24 UTC, StefanBabukov approved these changes

2021-03-08 17:58 UTC, merged