Fix legends
hms-dbmi-cellenics/ui pull request #175
Opened 2021-03-26 18:55 UTC by cosa65

# Background
#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-540

#### Link to staging deployment URL 

#### Links to any Pull Requests related to this

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [x] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

2021-03-30 12:04 UTC, StefanBabukov requested changes

2021-03-30 12:04 UTC, StefanBabukov commented on src/utils/plotSpecs/generateFrequencySpec.js
> +        domain: [0, 100],
Does this line change not break the plot when you switch to count? The y axis should not be max 100 in this case.

2021-03-31 10:01 UTC, StefanBabukov approved these changes

2021-03-31 14:11 UTC, vickymorrison commented
Why are the cell set labels different in the categorical embedding and the frequency plot? In the frequency plot they match the cluster annotation from Data Exploration whereas in the categorial embedding they have a weird format that seems to be independent of the cluster annotation from Data Exploration (in other words, I renamed a cluster in data exploration and only the frequency plot updated, not the categorical embedding).

2021-03-31 14:14 UTC, cosa65 commented
> Why are the cell set labels different in the categorical embedding and the frequency plot? In the frequency plot they match the cluster annotation from Data Exploration whereas in the categorial embedding they have a weird format that seems to be independent of the cluster annotation from Data Exploration (in other words, I renamed a cluster in data exploration and only the frequency plot updated, not the categorical embedding).

The embedding is using internal ids instead of the names, I'll fix that and let you know

2021-03-31 19:12 UTC, vickymorrison commented
Very minor point - presumably it should say 'toggle labels' rather than 'toggle legend' here:
<img width="534" alt="Screenshot 2021-03-31 at 20 09 32" src="https://user-images.githubusercontent.com/74908153/113198012-4dcfa600-925d-11eb-9a9e-b4ebeb81dd92.png">

2021-04-01 08:22 UTC, vickymorrison approved these changes

2021-04-01 13:18 UTC, merged