not reloading experiments for old experiments without project UUID
hms-dbmi-cellenics/ui pull request #283
Opened 2021-05-26 14:55 UTC by kafkasl

# Background
#### Link to issue 

https://biomage.atlassian.net/browse/BIOMAGE-1017

#### Link to staging deployment URL 

# Changes
### Code changes

 Old experiments don't have a project so the activeProjectUuid will actually be an experiment  ID so the experiments load will fail this should be addressed by migrating experiments  for now, if the activeProjectUuid is not a Uuid it means that it's an old experiment and we should not try to load the experiments with it

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

2021-05-26 17:16 UTC, xverges approved these changes

2021-05-27 10:12 UTC, marcellp requested changes

2021-05-27 10:12 UTC, marcellp commented on src/pages/data-management/index.jsx
> +  const experimentsAreLoaded = activeProject?.experiments.every((experimentId) => experiments.ids.includes(experimentId));
This is going to be very inefficient, it's an O(n^2) lookup. Could you convert at least one of them into a Set (e.g. `experiments.ids`) and use `Set.has`?

2021-05-27 11:58 UTC, marcellp approved these changes

2021-05-27 11:59 UTC, merged