[DRAFT] Metadata show filtered cell numbers
hms-dbmi-cellenics/ui pull request #421
Opened 2021-08-02 13:16 UTC by cosa65

# Background
#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-1061

#### Link to staging deployment URL 

#### Links to any Pull Requests related to this

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

2021-08-03 10:28 UTC, robioson requested changes, later dismissed
It's so good to get this fixed, only a couple of comments

2021-08-03 10:28 UTC, robioson commented on src/components/data-exploration/cell-sets-tool/CellSetsTool.jsx
> +  const someGeneExpressionObj = _.find(geneExpressions, () => true);
What exactly are you doing here? `geneExpressions` is an array and my guess is you want an arbitrary element, right? Why not simply use `[0]`?

2021-08-03 10:28 UTC, robioson commented on src/__test__/components/data-exploration/cell-sets-tool/CellSetsTool.test.jsx
> +  // });
This should either be deleted or uncommented! (blocking)

2021-08-04 12:33 UTC, ivababukova commented on src/components/data-exploration/cell-sets-tool/CellSetsTool.jsx
> +    if (filteredCells.current.size) return;
what happens if the user goes back to data processing and changes the filters? Or if they decide to filter out the gene which expression we use in here to get filtered cells from? 
Will filteredCells get updated? Will another gene get selected?

2021-08-04 12:37 UTC, ivababukova commented on src/__test__/components/data-exploration/cell-sets-tool/CellSetsTool.test.jsx
>  });
We are also missing out unit tests to actually test out if this filtered cells functionality works.

2021-08-05 12:27 UTC, ivababukova commented on src/components/data-exploration/cell-sets-tool/CellSetsTool.jsx
>  import { BlockOutlined, MergeCellsOutlined, SplitCellsOutlined } from '@ant-design/icons';
can you add unit tests for this new filtered cells functionality?

2021-08-06 11:10 UTC, robioson commented
I've added tests. Still trying to figure out the issues where selecting all cells by metadata results in a count one fewer than selecting all clusters. I noticed that the union of all clusters includes cell index 0, whereas the union of all samples does not. Still investigating this.

2021-08-06 11:36 UTC, ivababukova commented
> I've added tests. Still trying to figure out the issues where selecting all cells by metadata results in a count one fewer than selecting all clusters. I noticed that the union of all clusters includes cell index 0, whereas the union of all samples does not. Still investigating this.

Code looks good. If you are confident that this bug is not caused by the changes that we are introducing with this PR, let's merge this PR and tackle the bug as part of a different ticket. What do you think, James?

2021-08-06 11:37 UTC, ivababukova approved these changes

2021-08-06 12:00 UTC, robioson commented on src/components/data-exploration/cell-sets-tool/CellSetsTool.jsx
> +    if (filteredCells.current.size) return;
Very good catch, based on my testing you are correct that this was an issue. I removed the guard and confirmed that the `useEffect` only gets called once upon page load anyway.

2021-08-06 12:00 UTC, merged

2021-08-06 12:01 UTC, robioson commented
I think this is the correct approach @ivababukova. I will create a ticket.

2021-08-06 13:07 UTC, ivababukova commented on src/components/data-exploration/cell-sets-tool/CellSetsTool.jsx
> +    if (filteredCells.current.size) return;
nice one!