Fix bug and console warnings
hms-dbmi-cellenics/ui pull request #58
Opened 2020-12-18 12:34 UTC by ivababukova

# Background
#### Link to issue 

#### Link to staging deployment URL 

#### Links to any Pull Requests related to this

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

2020-12-18 13:01 UTC, StefanBabukov requested changes

2020-12-18 13:01 UTC, StefanBabukov commented on src/redux/reducers/plots/initialState.js
> +  legendOptions: ['top-bot'],
Why as an array?

2021-01-13 13:36 UTC, marcellp commented
@ivababukova what's the state on this? I assume there's so many merge conflicts it's probably stale.

2021-01-13 13:40 UTC, ivababukova commented
I think that we should close it ... it is too stale to be worth bothering

2021-01-13 13:40 UTC, closed without merging